kind: pipeline
name: default

steps:
  - name: frontend
    image: node:18.19.0
    commands:
      - npm install --registry=https://registry.npm.taobao.org
      - npm run build
  - name: docker
    image: plugins/docker
    settings:
      repo: registry.ops.ycyaw.com/project/ssvweb
      registry: registry.ops.ycyaw.com
      insecure: true
      force_tag: true
      tags: latest
