kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: registry.ops.ycyaw.com/project/ssvweb
      registry: registry.ops.ycyaw.com
      insecure: true
      force_tag: true
      tags: latest
